spring:
  application:
    name: projetobuscadiploma

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BuscaDiploma;TrustServerCertificate=true
    username: sa
    password: "Jo@o39052016"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
